# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# 默认缩放因子：建议初学者保持 0.1，确保运动安全缓慢。
# 以后想让机械臂跑快点，可以将这两个值改大（最大 1.0）。
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

# 关节属性设置
# [has_velocity_limits, has_acceleration_limits] 必须为 true，MoveIt 才能计算时间轨迹。
joint_limits:
  arm_joint1:
    has_velocity_limits: true
    max_velocity: 10.472
    has_acceleration_limits: true  # 修改为 true
    max_acceleration: 2.26         # 对应峰值角加速度 2.26 rad/s²
  arm_joint2:
    has_velocity_limits: true
    max_velocity: 12.5664
    has_acceleration_limits: true  # 修改为 true
    max_acceleration: 3.27         # 对应峰值角加速度 3.27 rad/s²
  arm_joint3:
    has_velocity_limits: true
    max_velocity: 10.472
    has_acceleration_limits: true  # 修改为 true
    max_acceleration: 2.26         # 对应峰值角加速度 2.26 rad/s²
  arm_joint4:
    has_velocity_limits: true
    max_velocity: 32.9867
    has_acceleration_limits: true  # 修改为 true
    max_acceleration: 32.99        # 对应峰值角加速度 32.99 rad/s²
  arm_joint5:
    has_velocity_limits: true
    max_velocity: 32.9867
    has_acceleration_limits: true  # 修改为 true
    max_acceleration: 32.99        # 对应峰值角加速度 32.99 rad/s²
  arm_joint6:
    has_velocity_limits: true
    max_velocity: 32.9867
    has_acceleration_limits: true  # 修改为 true
    max_acceleration: 32.99        # 对应峰值角加速度 32.99 rad/s²