# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    a1x_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

a1x_group_controller:
  ros__parameters:
    joints:
      - arm_joint1
      - arm_joint2
      - arm_joint3
      - arm_joint4
      - arm_joint5
      - arm_joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true